all: indices.csv points.csv
	@echo "---"
	@cat indices.csv
	@echo "---"
	@cat points.csv
	@echo "---"


clean: indices.csv points.csv
	echo "tag,index" > indices.csv
	echo "tag,points,inv" > points.csv
